site_name: Inuyasha's TechBlog
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax_config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.css
nav:
  - Home: index.md
  - Docker:
    - Dockerfile 构建经验: Docker/dockerfile_construct.md
    - Docker镜像部署与发布: Docker/docker_image_container.md
  - Lean4 : 
    - 同python对照的lean4教程: Lean4/Lean4_Python.md
    - 使用lean4求解Leetcode: Lean4/LeetCode.md
    - 使用lean4解数学方程: Lean4/LeanFunction.md
  - Lean Agent: lean_agent.md
  - Eval Agent: eval_agent.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InuyashaYang/TechBlog-of-Inuyasha
      text: Star on GitHub
